import { findBabies } from "@/lib/db/data-repositories/baby";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useParams, usePathname } from "next/navigation";
import Sidebar from "@/components/navigation/sidebar";
import Navbar from "@/components/navigation/navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) {
  const babies = await findBabies({});
  return (
    <html lang="en">
      <body
        className={`${inter.variable} bg-white dark:bg-gradient-to-r from-slate-900 to-zinc-600`}
      >
        <Navbar />
        <main className="flex mt-12">
          <section id="main-content" className="container mx-auto pt-8">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
