import { findBabies } from "@/lib/db/data-repositories/baby";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useParams, usePathname } from "next/navigation";
import Sidebar from "@/components/navigation/sidebar";
import Navbar from "@/components/navigation/navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) {
  const babies = await findBabies({});
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Navbar />
        <main className="flex">
          <section
            id="sidebar"
            className="w-64 border-r border-slate-900/10 h-screen fixed"
          >
            <Sidebar babies={babies} />
          </section>
          <section id="main-content" className="ml-72 w-full pt-8 mr-24">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
